### ISSUE TITLE
Tracking issue for rustc integration MVP

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/wg-traits#18]
### What do we mean by MVP?

* rustc types are converted to chalk types deeply and eagerly
* region integration is basically ignored, so not sound
* chalk is responsible for generating builtin trait rules, and those may be approximated in some cases
* constants are not handled, they are translated to `()` type for now
* closures and the fn traits are "reach items"
* unsizing is out of scope

### Work items

* [ ] Write code to eagerly, deeply convert rustc types to chalk types
* [ ] Extend `TypeName` with builtin types https://github.com/rust-lang/chalk/issues/368
* [ ] Extend chalk with support for builtin traits https://github.com/rust-lang/chalk/issues/363
* [ ] Some kind of interim solution `*Outlives` and `Subtype`
* [x] Land @jackh726's branch :)
